name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js (optional)
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies (if package.json exists)
      run: |
        if [ -f package.json ]; then npm ci; else echo "No package.json, skipping install"; fi

    - name: Run tests (if defined)
      run: |
        if [ -f package.json ] && grep -q "\"test\"" package.json; then npm test; else echo "No tests defined, skipping"; fi

    - name: Lint (example)
      run: |
        echo "Add lint steps relevant to your project (eslint, flake8, etc.)"